### ISSUE TITLE
Bug with CC0009 when using the created object in the initialization

### ISSUE THREAD

**Issue by AdrianoRNascimento** [code-cracker/code-cracker#525]
When the variable declaration does not have an initializer, and it is assigned, `CC0009` is incorrectly triggered. This should not raise a diagnostic for `CC0009`:

````csharp
class Foo
{
    public Foo F { get; set; }
    static void Baz()
    {
        Foo foo;
        foo = new Foo();
        foo.F = foo;
    }
}
````

We should check for that specific scenario. 

This should still raise a diagnostic:

````csharp
class Foo
{
    public Foo F { get; set; }
    static void Baz()
    {
        Foo foo;
        foo = Whatever();
        foo = new Foo();
        foo.F = foo;
    }
}
````

When there is a prior assignment between the variable declaration and it's assignment (or the variable being passed as `ref` or `out` to a method) `CC0009` should still be raised.

This is a bug on the analyzer, not on the code fix provider.

**Comment by giggio** [comment]
@AdrianoRNascimento This has been fixed on alpha5, released on April/2015. It is a duplicate of #324. Are you on the latest version.

**Comment by AdrianoRNascimento** [comment]
@giggio I am using the latest version. See the image bellow.
Is there a possibility that this error occurs in the VS extension version of Code Cracker?

![image](https://cloud.githubusercontent.com/assets/6334126/10196410/304d3e46-6769-11e5-9184-ac13c5e7945c.png)

**Comment by giggio** [comment]
We just released a new one. Try that, see if it fixed it.
Also, check if you don't have codecracker also installed as a nuget package.

**Comment by AdrianoRNascimento** [comment]
Hi @giggio,
Unfortunatelly it didn't fix the issue. I checked for the nuget package and I'm not using it. Just the extension.
As you can see in the image bellow the extension is updated.
![image](https://cloud.githubusercontent.com/assets/6334126/10288082/19d943c8-6b6d-11e5-874c-1c256a2078ad.png)

**Comment by giggio** [comment]
Ok, I have managed to reproduce:
![bug](https://cloud.githubusercontent.com/assets/334958/10309653/2756b0f6-6c14-11e5-9bae-61de861df2e7.png)

What we fixed on #324 was when the variable was initialized with the declaration. That does not happen anymore. So, for example, this will not generate `CC0009`:

````csharp
class Foo
{
    public Foo F { get; set; }
    static void Bar()
    {
        var foo = new Foo();
        foo.F = foo;
    }
}
````

But when the variable declaration does not have an initializer, and it is assigned, this might happen. This is your scenario:

````csharp
class Foo
{
    public Foo F { get; set; }
    static void Baz()
    {
        Foo foo;
        foo = new Foo();
        foo.F = foo;
    }
}
````

So, yeah, it is a bug. We should check for that specific scenario. But only when there is no prior assignment anywhere (or the variable being passed as `ref` or `out` to a method). I will update your description and text so it is easier to find.

**Comment by giggio** [comment]
This was @AdrianoRNascimento original comment:

This is my code (it's a test initialization):
```
_controller = new AccountController(_wsFederationConfig, _sessionAuthModule.Object);
_controller.Url = _urlHelper.Object;
_controller.ControllerContext = new ControllerContext(_context.Object, new RouteData(), _controller);
```

It's being incorrectly changed to:
```
_controller = new AccountController(_wsFederationConfig, _sessionAuthModule.Object)
{
    Url = _urlHelper.Object,
    ControllerContext = new ControllerContext(_context.Object, new RouteData(), _controller)
};
```

Note that when setting the "ControllerContext" property the "_controller" variable is not initialized yet. This is throwing a NullArgumentException in the "ControllerContext" constructor.

Thank you for your great work. Code cracker is awesome.

**Comment by giggio** [comment]
Fixed!
